### PR TITLE
link added edit user profile on member dashboard and all changed to a…

### PR DESCRIPTION
**Pull request by tonyy007**
… href

#### Category
- [ ] Bug Fix
- [X] New Feature
- [ ] Hotfix

#### Related issues:
- fixes #225 

#### What does this PR do?

Redirected links on member portal to correct places.

#### Notes for Reviewer (@cdconn00)

Made links white instead of default blue.

### CODE REVIEW

**Review by cdconn00 — CHANGES_REQUESTED** [review]
Tony, 

See index-member.ejs lines 9-18, for how the a tag should work with the buttons.

- Pull your branch  (git pull) on ft-tony-completedDashboard
- Make the rest of the buttons both of index-member.ejs, and index.ejs follow this format
- Remove the underlining from the text when you hover over the buttons 
- add, commit, and push changes
- When done come back to this PR and hit re-request review again

**Comment by tonyy007** [comment]
I have pushed my changes.

**Comment by cdconn00** [comment]
@tonyy007 Nice job so far, couple more things:

Screenshot_1

- Remove spaces around href, ie `href = "./link"` should be `href="./link"`
- You have a couple a tags that have two end tags (`</a>`), make sure that the ending is like the first tag in the screenshot
- These changes also need to be applied to views/portal/index.ejs
- Change colors to be white

Let me know if you have questions, and I can answer them.

**Comment by tonyy007** [comment]
Updated

**Review by cdconn00 — APPROVED** [review]

**Pull request merged**
